#!/bin/bash

BASE_COLLECTION_PATH="/must-gather"
SOSREPORT_DUMP_PATH=${OUT:-"${BASE_COLLECTION_PATH}/node_sosreports"}

mkdir -p $SOSREPORT_DUMP_PATH 2>/dev/null

LABEL=""
while getopts "l:" OPTION; do
    case $OPTION in
    l)
        LABEL="-l $OPTARG"
        ;;
    esac
done

oc get nodes $LABEL > $SOSREPORT_DUMP_PATH/oc_get_nodes.txt
